### PR TITLE
 Adding support for authorization code flow

### PR DESCRIPTION
**Pull request by scr4bble**
Issue https://github.com/helpscout/helpscout-api-php/issues/98

https://developer.helpscout.com/mailbox-api/overview/authentication/

### CODE REVIEW

**Comment by bkuhl** [comment]
Thanks for contributing!  This is on my radar to check out and manually test.  Could you add some unit tests to this?

**Comment by scr4bble** [comment]
No problem :)
Sorry, Ben, but I don't really have time for writing unit tests. I tested the code in our app and it is working just fine. I also tried to keep the conventions of your code so it looks nice.

**Comment by bkuhl** [comment]
Thanks for putting some effort towards this.  I'm merging it into another branch so I can add some tests and make a slight change to the implementation to make it more clear a code is a one-time use thing.

**Comment by bkuhl** [comment]
I just opened the PR - https://github.com/helpscout/helpscout-api-php/pull/109.  I'd say it'll be merged this week for sure, exact timing depends on PR approval

**Comment by scr4bble** [comment]
That sounds great! Thank you :)

**Pull request merged**
