### PR TITLE
Refactor method names to reflect functionality for assigning convos

### PR DESCRIPTION
**Pull request by griffithben**
Changelog:

- Calling `$conversation->setAssignee($user)` will internally call `$this->setAssignTo($user->getId());`
- Note about deprecating `setAssignTo()` to a more descriptive `setAssigneeId()` 
- Tests updated to reflect changes.

Solves Issue #111

### CODE REVIEW

**Comment by bkuhl** [comment]
This looks good, thanks for tackling it!  I do think to avoid breaking changes we should maintain `$conversation->setAssignTo()`, flag it as deprecated, and maintain test coverage for it until we are ready to do a major version bump.  Can you make those changes and then we'll get it merged?

**Comment by bkuhl** [comment]
Yes please!

**Comment by bkuhl** [comment]
The `v2` branch is now `master` so if you would adjust this PR to merge into `master` that would be great!

**Comment by griffithben** [comment]
@bkuhl done and done!

**Pull request merged**
