### PR TITLE
Repeat the request with new auth headers

### PR DESCRIPTION
**Pull request by scr4bble**
"If the request fails due to an authentication error, retry again after refreshing the token"
The "retry" should happen on the old Request object with new auth headers.

### CODE REVIEW

**Comment by scr4bble** [comment]
Fixing this issue: https://github.com/helpscout/helpscout-api-php/issues/279

**Comment by scr4bble** [comment]
@bkuhl would you have time for a fast review and merge of this fix? :)

**Comment by scr4bble** [comment]
Any update on this please?

**Comment by miguelrs** [comment]
Hey @scr4bble, sorry for the delay. Thanks for submitting this PR! ❤️  
We're looking into it and making some tests, and will update you as soon as we can.

**Comment by miguelrs** [comment]
@scr4bble We've merged your changes (after adding a small test for them). Thanks again for submitting the PR and for your patience. Please let us know if you experience any issues.

**Pull request merged**
