### PR TITLE
Fix array on line 338

### PR DESCRIPTION
**Pull request by acdciron59**

### CODE REVIEW

**Comment by acdciron59** [comment]
Added a key pair 'fields' for $fields to parse by getParams().

**Comment by stevenwadejr** [comment]
What is this PR trying to do? I don't see any added value.

* `$params` isn't defined as an array before you're trying to set the keys/values
* `$this->getParams(array('fields' => $fields, 'page' => $page))` works just fine inline, breaking it out into a `$params` array doesn't add anything here.

**Comment by acdciron59** [comment]
Replace the $fields as an empty array instead of null. and revert back to inline declaration.

**Comment by stevenwadejr** [comment]
Closing this. While `$fields=array()` adds more value, it's not consistent with the rest of the code, and we're not prepared to update all instances at this point.

**Pull request closed without merging**
